version: "3.8"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt